services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "bebrotype"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - bebrotype-data:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "bebra@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "bebra"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: always
    networks:
      - postgres

  app:
    build: packages/app
    ports:
      - 3000:3000

  server:
    build: packages/server
    ports:
      - 3001:3001
    depends_on:
      - db
    networks:
      - postgres

volumes:
  bebrotype-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
