[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = {version = "0.6.18", features = ["macros", "multipart"] }
tokio = {version = "1.28.2", features = ["full"] }
tokio-util = {version = "0.7.8", features = ["io"]}
tower = "0.4.13"
tower-http = {version = "0.4.3", features = ["cors", "fs", "trace", "compression-br"]}
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0"
hyper = { version = "0.14.26", features = ["full"] }
diesel = { version = "2.1.0", features = ["postgres"] }
diesel-async = { version = "0.3.1", features = ["postgres", "deadpool"] }
magic-crypt = "3.1.12"
jsonwebtoken = "8.3.0"
chrono = "0.4.26"
dotenvy = "0.15.7"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"]}
validator = "0.16.1"

